spring.application.name=stash


spring.datasource.url=jdbc:mysql://awseb-e-tpfeqwavds-stack-awsebrdsdatabase-aiyitxvcwucp.cz02woiwujfm.us-east-2.rds.amazonaws.com:3306/ebdb
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


server.port = 8080
